apiVersion: batch/v1
kind: Job
metadata:
  name: mongoutil-mongorestore
spec:
  template:
    spec:
      containers:
      - name: mongoutil-mongorestore
        image: bitnami/mongodb
        command: ["mongorestore", "--host", "mongodb-mongodb", "--password",  "password", "--verbose", "/dump"]
        volumeMounts:
        - mountPath: "/dump"
          name: mongodump
      volumes:
      - name: mongodump
        persistentVolumeClaim:
          claimName: mongoutil-mongodump
      restartPolicy: Never
  backoffLimit: 4